# Number of days of inactivity before an issue becomes stale
daysUntilStale: 20

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 10 

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions. Please do not hesitate to re-open this issue or create
  a new one if this issue is still relevant. Thanks!

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
