source "https://rubygems.org"
gem "jekyll", "~> 3.8.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?
gem "just-the-docs", "0.2.7"

